services:
  postgres-tenant:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak-tenant:
    image: quay.io/keycloak/keycloak:22.0.1
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
    command: start-dev
    ports:
      - "8084:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data

  app:
    image: ${DOCKER_REGISTRY:-hemanthkumar21}/${IMAGE_NAME:-application_services_app}:${BUILD_NUMBER}
    build:
      context: .
      dockerfile: services/tenant_user-service/Dockerfile
      args:
        - BUILD_VERSION=${BUILD_NUMBER}
    command: uvicorn tenant_user_service.main:app --host 0.0.0.0 --reload
    env_file:
      - ./.env
    volumes:
      - ./services/tenant_user-service:/app
    ports:
      - "8009:8000"
    depends_on:
      - postgres-tenant
      - keycloak-tenant

  migrate:
    image: ${DOCKER_REGISTRY:-hemanthkumar21}/${IMAGE_NAME:-application_services_app}:${BUILD_NUMBER}
    build:
      context: .
      dockerfile: services/tenant_user-service/Dockerfile
      args:
        - BUILD_VERSION=${BUILD_NUMBER}
    command: alembic -c /app/alembic.ini upgrade head
    env_file:
      - ./.env
    depends_on:
      postgres-tenant:
        condition: service_healthy

volumes:
  postgres_data:
  keycloak_data:
