apiVersion: v1
kind: Service
metadata:
  name: tenant-user-service
  namespace: application-services
spec:
  selector:
    app: tenant-user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer